# Generated by Django 5.1.1 on 2024-10-23 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='authentication',
            name='address',
            field=models.CharField(blank=True, default=None, max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='authentication',
            name='area_code',
            field=models.CharField(blank=True, default=None, max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='authentication',
            name='rent',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
    ]
