# Generated by Django 5.1.1 on 2024-10-23 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0004_alter_authentication_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='authentication',
            name='address',
            field=models.CharField(default='None', max_length=120),
        ),
        migrations.AlterField(
            model_name='authentication',
            name='area_code',
            field=models.CharField(default='None', max_length=120),
        ),
    ]
