# Generated by Django 5.1.1 on 2024-10-23 20:27

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0005_alter_authentication_address_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='authentication',
            name='profile_picture',
            field=cloudinary.models.CloudinaryField(default='default_profile_rkmhff', max_length=255, verbose_name='images'),
        ),
    ]
